import type { AboutData } from './types'

export const bratislavaAbout: AboutData = {
  topics: {
    ru: 'архитектура, история, замки, музеи, парки, культура',
    en: 'architecture, history, castles, museums, parks, culture',
  },
  // Order preserved from the standalone site. Note: the original page-about.ts
  // carried a description for `divadelneprechadzky.theatre.sk` that was never
  // listed, so it never rendered; it is left out here rather than silently added.
  sources: [
    { domain: 'visitbratislava.com',      ru: 'Официальный туристический портал',                                        en: 'Official tourism portal' },
    { domain: 'welcometobratislava.eu',   ru: 'Независимый путеводитель по Братиславе',                                  en: 'Independent Bratislava guide' },
    { domain: 'bratislava.sk',            ru: 'Официальный сайт города Братислава',                                      en: 'Official website of the city of Bratislava' },
    { domain: 'sk.wikipedia.org',         ru: 'Словацкая Википедия',                                                     en: 'Slovak Wikipedia' },
    { domain: 'en.wikipedia.org',         ru: 'Английская Википедия',                                                    en: 'English Wikipedia' },
    { domain: 'hu.wikipedia.org',         ru: 'Венгерская Википедия',                                                    en: 'Hungarian Wikipedia' },
    { domain: 'cs.wikipedia.org',         ru: 'Чешская Википедия',                                                       en: 'Czech Wikipedia' },
    { domain: 'commons.wikimedia.org',    ru: 'Викисклад',                                                               en: 'Wikimedia Commons' },
    { domain: 'register-architektury.sk', ru: 'Реестр современной словацкой архитектуры',                                en: 'Register of modern Slovak architecture' },
    { domain: 'muop.eu',                  ru: 'Городской институт охраны памятников',                                    en: 'City Institute for Monument Protection' },
    { domain: 'muzeum.sk',                ru: 'Каталог музеев Словакии',                                                 en: 'Directory of Slovak museums' },
    { domain: 'bratislavskenoviny.sk',    ru: 'Городская газета Братиславы',                                             en: 'Bratislava city newspaper' },
    { domain: 'bratislavaden.sk',         ru: 'Городское онлайн-издание Братиславы',                                     en: 'Bratislava online news site' },
    { domain: 'sme.sk',                   ru: 'Словацкая газета, братиславская рубрика',                                  en: 'Slovak daily, Bratislava section' },
    { domain: 'pozsonyikifli.sk',         ru: 'Краеведческий журнал о Братиславе',                                       en: 'Local-history journal about Bratislava' },
    { domain: 'umeniemesta.sk',           ru: 'База данных искусства в общественном пространстве',                       en: 'Database of art in public space' },
    { domain: 'bratislavastory.com',      ru: 'Блог городских историй Братиславы',                                       en: 'Blog of Bratislava city stories' },
    { domain: 'citylife.sk',              ru: 'Афиша событий Братиславы',                                                en: 'Bratislava events guide' },
    { domain: 'vopz.sk',                  ru: 'Портал «Викенда открытых парков и садов»',                                en: 'Open Parks and Gardens Weekend portal' },
    { domain: 'fotorado.sk',              ru: 'Фотоблог о Словакии',                                                     en: 'Photo blog about Slovakia' },
    { domain: 'parallaxaview.com',        ru: 'Фотоблог о путешествиях и архитектуре',                                   en: 'Travel and architecture photo blog' },
    { domain: 'vlaky.net',                ru: 'Железнодорожный портал',                                                  en: 'Railway community portal' },
    { domain: 'atlasobscura.com',         ru: 'Атлас скрытых чудес мира',                                                en: 'Atlas of the world’s hidden wonders' },
    { domain: 'muzeum.racan.sk',          ru: 'Рачанское музейное общество',                                             en: 'Rača local-history museum society' },
    { domain: 'kriz.epocha.sk',           ru: 'Каталог сакральных памятников Словакии',                                  en: 'Catalogue of Slovakia’s sacral monuments' },
    { domain: 'pam.epocha.sk',            ru: 'Каталог мемориалов Словакии',                                             en: 'Catalogue of Slovakia’s memorials' },
    { domain: 'beliana.sav.sk',           ru: 'Словацкая универсальная энциклопедия (САН)',                              en: 'Slovak general encyclopedia (SAV)' },
    { domain: 'slovakia.travel',          ru: 'Официальный туристический портал Словакии',                               en: 'Official tourism portal of Slovakia' },
    { domain: 'bratislavaguide.com',      ru: 'Путеводитель по Братиславе',                                              en: 'Bratislava city guide' },
    { domain: 'bainfo.sk',                ru: 'Каталог достопримечательностей Братиславы и окрестностей',                en: 'Catalogue of Bratislava-region sights' },
    { domain: 'slovago.sk',               ru: 'Портал поездок по Словакии',                                              en: 'Slovak trips and experiences portal' },
    { domain: 'svu.sk',                   ru: 'Словацкий союз художников',                                               en: 'Slovak Union of Visual Arts' },
    { domain: 'peme.sk',                  ru: 'Сайт скульптора Петера Месароша',                                        en: 'Sculptor Peter Mészároš’s site' },
    { domain: 'galeria19.sk',             ru: 'Галерея современного искусства Galéria 19',                               en: 'Galéria 19 contemporary art gallery' },
    { domain: 'kastielcunovo.sk',         ru: 'Экоцентр Чуново (Братиславский край)',                                    en: 'Čunovo Ecocentre (Bratislava Region)' },
    { domain: 'cor.europa.eu',            ru: 'Европейский комитет регионов',                                            en: 'European Committee of the Regions' },
    { domain: 'vypadni.sk',               ru: 'Портал идей для прогулок по Словакии',                                    en: 'Slovak trip-ideas portal' },
    { domain: 'dubravka.sk',              ru: 'Официальный сайт городской части Дубравка',                               en: 'Official website of the Dúbravka borough' },
    { domain: 'bratislava.dnes24.sk',     ru: 'Новостной портал Братиславы',                                            en: 'Bratislava news portal' },
    { domain: 'mileticka.com',            ru: 'Сайт рынка Милетичова',                                                  en: 'Miletičova market website' },
    { domain: 'mileticka.sk',             ru: 'Салезианский приход на Милетичовой',                                      en: 'Salesian parish on Miletičova' },
    { domain: 'sustava.sk',               ru: 'Модель Солнечной системы в Братиславе',                                   en: 'Solar system model in Bratislava' },
    { domain: 'app.geology.sk',           ru: 'Атлас декоративных камней (Государственный геологический институт)',      en: 'Decorative stones atlas (State Geological Institute)' },
    { domain: 'opive.sk',                 ru: 'Словацкий пивной журнал',                                                 en: 'Slovak beer magazine' },
    { domain: 'balove.sk',                ru: 'Блог фотоисторий о Братиславе',                                           en: 'Bratislava photo-stories blog' },
    { domain: 'yimba.sk',                 ru: 'Журнал о девелопменте и архитектуре Братиславы',                          en: 'Bratislava development and architecture magazine' },
    { domain: 'podnavylet.sk',            ru: 'Портал идей для прогулок по Словакии',                                    en: 'Slovak trip-ideas portal' },
    { domain: 'storymaps.arcgis.com',     ru: 'Платформа интерактивных историй ArcGIS',                                  en: 'ArcGIS StoryMaps platform' },
  ],
}
