import type { AboutData } from './types'

export const bratislavaAbout: AboutData = {
  topics: {
    ru: 'архитектура, история, замки, музеи, парки, культура',
    en: 'architecture, history, castles, museums, parks, culture',
  },
  // Order preserved from the standalone site. Note: the original page-about.ts
  // carried a description for `divadelneprechadzky.theatre.sk` that was never
  // listed, so it never rendered; it is left out here rather than silently added.
  sources: [
    { domain: 'visitbratislava.com',            ru: 'Официальный туристический портал',                                     en: 'Official tourism portal' },
    { domain: 'welcometobratislava.eu',         ru: 'Независимый путеводитель по Братиславе',                               en: 'Independent Bratislava guide' },
    { domain: 'bratislava.sk',                  ru: 'Официальный сайт города Братислава',                                   en: 'Official website of the city of Bratislava' },
    { domain: 'staremesto.sk',                  ru: 'Официальный сайт городской части Старе-Место',                         en: 'Official website of the Staré Mesto borough' },
    { domain: 'sk.wikipedia.org',               ru: 'Словацкая Википедия',                                                  en: 'Slovak Wikipedia' },
    { domain: 'en.wikipedia.org',               ru: 'Английская Википедия',                                                 en: 'English Wikipedia' },
    { domain: 'hu.wikipedia.org',               ru: 'Венгерская Википедия',                                                 en: 'Hungarian Wikipedia' },
    { domain: 'cs.wikipedia.org',               ru: 'Чешская Википедия',                                                    en: 'Czech Wikipedia' },
    { domain: 'commons.wikimedia.org',          ru: 'Викисклад',                                                            en: 'Wikimedia Commons' },
    { domain: 'register-architektury.sk',       ru: 'Реестр современной словацкой архитектуры',                             en: 'Register of modern Slovak architecture' },
    { domain: 'muop.eu',                        ru: 'Городской институт охраны памятников',                                 en: 'City Institute for Monument Protection' },
    { domain: 'muzeum.sk',                      ru: 'Каталог музеев Словакии',                                              en: 'Directory of Slovak museums' },
    { domain: 'bratislavskenoviny.sk',          ru: 'Городская газета Братиславы',                                          en: 'Bratislava city newspaper' },
    { domain: 'bratislavaden.sk',               ru: 'Городское онлайн-издание Братиславы',                                  en: 'Bratislava online news site' },
    { domain: 'sme.sk',                         ru: 'Словацкая газета, братиславская рубрика',                              en: 'Slovak daily, Bratislava section' },
    { domain: 'pozsonyikifli.sk',               ru: 'Краеведческий журнал о Братиславе',                                    en: 'Local-history journal about Bratislava' },
    { domain: 'umeniemesta.sk',                 ru: 'База данных искусства в общественном пространстве',                    en: 'Database of art in public space' },
    { domain: 'bratislavastory.com',            ru: 'Блог городских историй Братиславы',                                    en: 'Blog of Bratislava city stories' },
    { domain: 'citylife.sk',                    ru: 'Афиша событий Братиславы',                                             en: 'Bratislava events guide' },
    { domain: 'vopz.sk',                        ru: 'Портал «Викенда открытых парков и садов»',                             en: 'Open Parks and Gardens Weekend portal' },
    { domain: 'fotorado.sk',                    ru: 'Фотоблог о Словакии',                                                  en: 'Photo blog about Slovakia' },
    { domain: 'parallaxaview.com',              ru: 'Фотоблог о путешествиях и архитектуре',                                en: 'Travel and architecture photo blog' },
    { domain: 'vlaky.net',                      ru: 'Железнодорожный портал',                                               en: 'Railway community portal' },
    { domain: 'atlasobscura.com',               ru: 'Атлас скрытых чудес мира',                                             en: 'Atlas of the world\'s hidden wonders' },
    { domain: 'muzeum.racan.sk',                ru: 'Рачанское музейное общество',                                          en: 'Rača local-history museum society' },
    { domain: 'kriz.epocha.sk',                 ru: 'Каталог сакральных памятников Словакии',                               en: 'Catalogue of Slovakia\'s sacral monuments' },
    { domain: 'pam.epocha.sk',                  ru: 'Каталог мемориалов Словакии',                                          en: 'Catalogue of Slovakia\'s memorials' },
    { domain: 'doew.at',                        ru: 'Архив документации австрийского Сопротивления',                        en: 'Documentation Centre of Austrian Resistance' },
    { domain: 'petrzalka.sk',                   ru: 'Официальный сайт городской части Петржалка',                           en: 'Official website of the Petržalka borough' },
    { domain: 'beliana.sav.sk',                 ru: 'Словацкая универсальная энциклопедия (САН)',                           en: 'Slovak general encyclopedia (SAV)' },
    { domain: 'slovakia.travel',                ru: 'Официальный туристический портал Словакии',                            en: 'Official tourism portal of Slovakia' },
    { domain: 'bratislavaguide.com',            ru: 'Путеводитель по Братиславе',                                           en: 'Bratislava city guide' },
    { domain: 'bainfo.sk',                      ru: 'Каталог достопримечательностей Братиславы и окрестностей',             en: 'Catalogue of Bratislava-region sights' },
    { domain: 'slovago.sk',                     ru: 'Портал поездок по Словакии',                                           en: 'Slovak trips and experiences portal' },
    { domain: 'svu.sk',                         ru: 'Словацкий союз художников',                                            en: 'Slovak Union of Visual Arts' },
    { domain: 'peme.sk',                        ru: 'Сайт скульптора Петера Месароша',                                      en: 'Sculptor Peter Mészároš\'s site' },
    { domain: 'galeria19.sk',                   ru: 'Галерея современного искусства Galéria 19',                            en: 'Galéria 19 contemporary art gallery' },
    { domain: 'webumenia.sk',                   ru: 'Собрания словацких галерей онлайн',                                    en: 'Online collections of Slovak galleries' },
    { domain: 'romanfecikgallery.sk',           ru: 'Галерея Романа Фецика в Братиславе',                                   en: 'Roman Fecik Gallery, Bratislava' },
    { domain: 'gib-bratislava.eu',              ru: 'Генеральный инвестор Братиславы (городская строительная организация)', en: 'Bratislava\'s general investor (city construction authority)' },
    { domain: 'kastielcunovo.sk',               ru: 'Экоцентр Чуново (Братиславский край)',                                 en: 'Čunovo Ecocentre (Bratislava Region)' },
    { domain: 'cor.europa.eu',                  ru: 'Европейский комитет регионов',                                         en: 'European Committee of the Regions' },
    { domain: 'vypadni.sk',                     ru: 'Портал идей для прогулок по Словакии',                                 en: 'Slovak trip-ideas portal' },
    { domain: 'dubravka.sk',                    ru: 'Официальный сайт городской части Дубравка',                            en: 'Official website of the Dúbravka borough' },
    { domain: 'bratislava.dnes24.sk',           ru: 'Новостной портал Братиславы',                                          en: 'Bratislava news portal' },
    { domain: 'mileticka.com',                  ru: 'Сайт рынка Милетичова',                                                en: 'Miletičova market website' },
    { domain: 'mileticka.sk',                   ru: 'Салезианский приход на Милетичовой',                                   en: 'Salesian parish on Miletičova' },
    { domain: 'sustava.sk',                     ru: 'Модель Солнечной системы в Братиславе',                                en: 'Solar system model in Bratislava' },
    { domain: 'app.geology.sk',                 ru: 'Атлас декоративных камней (Государственный геологический институт)',   en: 'Decorative stones atlas (State Geological Institute)' },
    { domain: 'opive.sk',                       ru: 'Словацкий пивной журнал',                                              en: 'Slovak beer magazine' },
    { domain: 'balove.sk',                      ru: 'Блог фотоисторий о Братиславе',                                        en: 'Bratislava photo-stories blog' },
    { domain: 'yimba.sk',                       ru: 'Журнал о девелопменте и архитектуре Братиславы',                       en: 'Bratislava development and architecture magazine' },
    { domain: 'asb.sk',                         ru: 'Словацкий журнал об архитектуре и строительстве',                      en: 'Slovak architecture and construction magazine' },
    { domain: 'podnavylet.sk',                  ru: 'Портал идей для прогулок по Словакии',                                 en: 'Slovak trip-ideas portal' },
    { domain: 'storymaps.arcgis.com',           ru: 'Платформа интерактивных историй ArcGIS',                               en: 'ArcGIS StoryMaps platform' },
    { domain: 'velkykostol.sk',                 ru: 'Сайт евангелического прихода Старе-Места',                             en: 'Lutheran congregation of Bratislava Staré Mesto' },
    { domain: 'stuba.sk',                       ru: 'Словацкий технический университет в Братиславе',                       en: 'Slovak University of Technology in Bratislava' },
    { domain: 'novacvernovka.eu',               ru: 'Культурно-креативный центр «Новая Цверновка»',                         en: 'Nová Cvernovka cultural and creative centre' },
    { domain: 'dobremesto.gov.sk',              ru: 'Государственный портал об обновлении городских территорий',            en: 'State portal on urban regeneration' },
    { domain: 'amazingarchitecture.com',        ru: 'Международный журнал архитектурных проектов',                          en: 'International architecture project magazine' },
    { domain: 'krizom-krazom.online',           ru: 'Каталог памятников и достопримечательностей Словакии',                 en: 'Catalogue of Slovak monuments and sights' },
    { domain: 'archinfo.sk',                    ru: 'База данных и журнал словацкой архитектуры',                           en: 'Slovak architecture database and magazine' },
    { domain: 'zsceska.sk',                     ru: 'Сайт школы на Ческой улице',                                           en: 'Website of the school on Česká street' },
    { domain: 'divadelneprechadzky.theatre.sk', ru: 'Театральные прогулки Театрального института',                          en: 'Theatre walks project of the Theatre Institute' },
    { domain: 'vajnory.sk',                     ru: 'Официальный сайт городской части Вайноры',                             en: 'Official website of the Vajnory borough' },
  ],
}
