import type { AboutData } from './types'

export const budapestAbout: AboutData = {
  topics: {
    ru: 'архитектура, история, музеи, купальни, парки, культура',
    en: 'architecture, history, museums, thermal baths, parks, culture',
  },
  sources: [
    { domain: 'welovebudapest.com',           ru: 'Городской журнал о Будапеште',                               en: 'Budapest city magazine' },
    { domain: 'budappest.hu',                 ru: 'Журнал о Будапеште',                                         en: 'Budapest magazine' },
    { domain: 'funzine.hu',                   ru: 'Журнал о местах и событиях',                                 en: 'Places and events magazine' },
    { domain: 'turistamagazin.hu',            ru: 'Туристический журнал',                                       en: 'Tourism magazine' },
    { domain: 'termalfurdo.hu',               ru: 'Справочник термальных купален',                              en: 'Thermal bath directory' },
    { domain: 'termalonline.hu',              ru: 'Новостной портал о термальных купальнях',                    en: 'Thermal bath news portal' },
    { domain: 'pestbuda.hu',                  ru: 'Портал об истории и урбанистике города',                     en: 'Urban history portal' },
    { domain: 'epiteszforum.hu',              ru: 'Портал об архитектуре',                                      en: 'Architecture portal' },
    { domain: 'architextura.hu',              ru: 'Блог об архитектуре',                                        en: 'Architecture blog' },
    { domain: 'varosilevego.blog.hu',         ru: 'Блог об урбанистике',                                        en: 'Urbanism blog' },
    { domain: '444.hu',                       ru: 'Новостной портал',                                           en: 'News portal' },
    { domain: 'budapest.hu',                  ru: 'Официальный сайт города Будапешт',                           en: 'Official website of the city of Budapest' },
    { domain: 'obuda.hu',                     ru: 'Официальный сайт III района',                                en: 'Official website of District III' },
    { domain: 'tabani.plebania.hu',           ru: 'Сайт табанского прихода',                                    en: 'Tabán parish website' },
    { domain: 'esztergomi-ersekseg.hu',       ru: 'Эстергом-Будапештская архиепархия',                          en: 'Archdiocese of Esztergom-Budapest' },
    { domain: 'bornegyed.hu',                 ru: 'Винный квартал Будафока',                                    en: 'The Budafok wine quarter' },
    { domain: 'zaborszky.co.hu',              ru: 'Будафокский погребной лабиринт, погреб Заборски',            en: 'Budafok cellar system, Záborszky cellar' },
    { domain: 'ybl.uni-obuda.hu',             ru: 'Университет Обуды, факультет им. Ибля',                      en: 'Óbuda University, Ybl Faculty' },
    { domain: 'hu.wikipedia.org',             ru: 'Венгерская Википедия',                                       en: 'Hungarian Wikipedia' },
    { domain: 'en.wikipedia.org',             ru: 'Английская Википедия',                                       en: 'English Wikipedia' },
    { domain: 'commons.wikimedia.org',        ru: 'Викисклад',                                                  en: 'Wikimedia Commons' },
    { domain: 'mandadb.hu',                   ru: 'Венгерский цифровой архив (MaNDA)',                          en: 'Hungarian Digital Archive (MaNDA)' },
    { domain: 'reformacio.mnl.gov.hu',        ru: 'Национальный архив: наследие Реформации',                    en: 'National Archives: Reformation heritage' },
    { domain: 'mult-kor.hu',                  ru: 'Журнал об истории',                                          en: 'History magazine' },
    { domain: 'papageno.hu',                  ru: 'Портал о культуре и академической музыке',                   en: 'Culture and classical music portal' },
    { domain: 'infostart.hu',                 ru: 'Новостной портал',                                           en: 'News portal' },
    { domain: 'parkerdo.hu',                  ru: 'Пилишский лесхоз: тропы и смотровые',                        en: 'Pilis State Forestry: trails and lookouts' },
    { domain: 'turabazis.hu',                 ru: 'Путеводитель по венгерским маршрутам',                       en: 'Hiking guide to Hungary' },
    { domain: 'csodahelyek.hu',               ru: 'Портал о путешествиях по Венгрии',                           en: 'Travel portal on Hungarian destinations' },
    { domain: 'mavcsoport.hu',                ru: 'Венгерские государственные железные дороги (MÁV)',           en: 'Hungarian State Railways (MÁV)' },
    { domain: 'telex.hu',                     ru: 'Новостной портал',                                           en: 'News portal' },
    { domain: 'index.hu',                     ru: 'Новостной портал',                                           en: 'News portal' },
    { domain: 'jozsefvarosujsag.hu',          ru: 'Районная газета Йожефвароша',                                en: 'District VIII local paper' },
    { domain: 'atlasobscura.com',             ru: 'Путеводитель по необычным местам',                           en: 'Guide to unusual places' },
    { domain: 'kozterkep.hu',                 ru: 'База венгерской городской скульптуры',                       en: 'Database of Hungarian public sculpture' },
    { domain: 'budavar.abtk.hu',              ru: 'Топография будайского Крепостного квартала',                 en: 'Topography of the Buda Castle District' },
    { domain: 'urania-nf.hu',                 ru: 'Национальный кинотеатр «Урания»',                            en: 'Uránia National Film Theatre' },
    { domain: 'forbes.hu',                    ru: 'Деловой журнал',                                             en: 'Business magazine' },
    { domain: 'hvg.hu',                       ru: 'Новостной еженедельник',                                     en: 'News weekly' },
    { domain: 'szombat.org',                  ru: 'Журнал венгерской еврейской культуры',                       en: 'Hungarian Jewish cultural magazine' },
    { domain: 'nori.gov.hu',                  ru: 'Институт национального наследия',                            en: 'National Heritage Institute' },
    { domain: 'mazsihisz.hu',                 ru: 'Союз венгерских еврейских общин',                            en: 'Federation of Hungarian Jewish Communities' },
    { domain: 'dreherzrt.hu',                 ru: 'Пивоваренные заводы Дреера',                                 en: 'Dreher Breweries' },
    { domain: 'csili.hu',                     ru: 'Дом культуры «Чили»',                                        en: 'Csili Cultural Centre' },
    { domain: 'sorbotkert.hu',                ru: 'Шорокшарский ботанический сад',                              en: 'Soroksár Botanical Garden' },
    { domain: 'budapestcity.org',             ru: 'База памятников Будапешта',                                  en: 'Budapest monuments database' },
    { domain: 'hipo.gov.hu',                  ru: 'Ведомство интеллектуальной собственности',                   en: 'Hungarian Intellectual Property Office' },
    { domain: 'mek.oszk.hu',                  ru: 'Венгерская электронная библиотека',                          en: 'Hungarian Electronic Library' },
    { domain: 'kispest.hu',                   ru: 'Сайт XIX района',                                            en: 'District XIX municipality' },
    { domain: 'muzeum.pesterzsebet.hu',       ru: 'Пештэржебетский музей',                                      en: 'Pesterzsébet Museum' },
    { domain: 'magyarmuzeumok.hu',            ru: 'Журнал о венгерских музеях',                                 en: 'Hungarian museums magazine' },
    { domain: 'fokert.budapestikozmuvek.hu',  ru: 'Городское садово-парковое управление',                       en: 'Budapest parks and gardens authority' },
    { domain: 'bpxv.hu',                      ru: 'Сайт XV района',                                             en: 'District XV municipality' },
    { domain: 'rakoscsaba.plebania.hu',       ru: 'Приход Ракошчабы',                                           en: 'Rákoscsaba parish' },
    { domain: 'csepelimunkasotthon.hu',       ru: 'Чепельский рабочий дом',                                     en: 'Csepel Workers’ Home' },
    { domain: 'rakospalotaimuzeum.hu',        ru: 'Музей Ракошпалоты',                                          en: 'Rákospalota Museum' },
    { domain: 'lexikon.katolikus.hu',         ru: 'Венгерский католический лексикон',                           en: 'Hungarian Catholic Lexicon' },
    { domain: 'kozepkoritemplom.hu',          ru: 'Средневековые церкви Венгрии',                               en: 'Medieval churches of Hungary' },
    { domain: 'pim.hu',                       ru: 'Литературный музей Петёфи',                                  en: 'Petőfi Literary Museum' },
    { domain: 'varosvedo.hu',                 ru: 'Общество защиты Будапешта',                                  en: 'Budapest City Protection Association' },
    { domain: 'tajhazigazgatosag.skanzen.hu', ru: 'Дирекция венгерских этнографических домов',                  en: 'Directorate of Hungarian Open-Air Collections' },
    { domain: 'arcanum.com',                  ru: 'Цифровая библиотека и лексиконы',                            en: 'Digital library and lexicons' },
    { domain: 'rothmuzeum.hu',                ru: 'Музей Миксы Рота',                                           en: 'Róth Miksa Museum' },
    { domain: 'kiscellimuzeum.hu',            ru: 'Музей Кишцелли',                                             en: 'Kiscelli Museum' },
    { domain: 'semmelweismuseum.hu',          ru: 'Музей истории медицины Земмельвейса',                        en: 'Semmelweis Museum of Medical History' },
    { domain: 'museum.hu',                    ru: 'Каталог венгерских музеев',                                  en: 'Hungarian museum directory' },
    { domain: 'budapest100.hu',               ru: 'Архив домов фестиваля «Будапешт-100»',                       en: 'Budapest100 festival house archive' },
    { domain: 'tomorylajos-muzeum.hu',        ru: 'Музей Лайоша Томори, XVIII район',                           en: 'Lajos Tomory Museum, District XVIII' },
    { domain: 'csepelivaroskep.hu',           ru: 'Учреждения культуры Чепеля',                                 en: 'Csepel district cultural institutions' },
    { domain: 'programturizmus.hu',           ru: 'Венгерский путеводитель по программам и музеям',             en: 'Hungarian programme and museum guide' },
    { domain: 'bp16.hu',                      ru: 'Самоуправление XVI района',                                  en: 'District XVI local government' },
    { domain: 'mnm.hu',                       ru: 'Венгерский национальный музей',                              en: 'Hungarian National Museum' },
    { domain: 'szepmuveszeti.hu',             ru: 'Музей изящных искусств',                                     en: 'Museum of Fine Arts' },
    { domain: 'mucsarnok.hu',                 ru: 'Выставочный зал Мючарнок',                                   en: 'Kunsthalle Budapest' },
    { domain: 'neprajz.hu',                   ru: 'Этнографический музей',                                      en: 'Museum of Ethnography' },
    { domain: 'mezogazdasagimuzeum.hu',       ru: 'Венгерский сельскохозяйственный музей',                      en: 'Hungarian Agricultural Museum' },
    { domain: 'zoobudapest.com',              ru: 'Будапештский зоопарк',                                       en: 'Budapest Zoo' },
    { domain: 'citadella.hu',                 ru: 'Цитадель на горе Геллерт',                                   en: 'The Citadella on Gellért Hill' },
    { domain: 'sziklatemplom.hu',             ru: 'Скальный храм',                                              en: 'The Rock Church' },
    { domain: 'dunaipoly.hu',                 ru: 'Национальный парк Дунай-Ипой',                               en: 'Duna-Ipoly National Park' },
    { domain: 'aquincum.hu',                  ru: 'Аквинкский музей и археологический парк',                    en: 'Aquincum Museum and Archaeological Park' },
    { domain: 'hyperion.szepmuveszeti.hu',    ru: 'Онлайн-собрание Музея изящных искусств',                     en: 'Museum of Fine Arts online collection' },
    { domain: 'gyermekvasut.hu',              ru: 'Детская железная дорога',                                    en: 'The Budapest Children Railway' },
    { domain: 'aeropark.hu',                  ru: 'Авиационный музей «Аэропарк»',                               en: 'Aeropark aviation museum' },
    { domain: 'mementopark.hu',               ru: 'Мементо-парк',                                               en: 'Memento Park' },
    { domain: 'mng.hu',                       ru: 'Венгерская национальная галерея',                            en: 'Hungarian National Gallery' },
    { domain: 'nagytetenyi.hu',               ru: 'Надьтетеньский замок-музей',                                 en: 'Nagytétény Castle Museum' },
    { domain: 'tropicarium.hu',               ru: 'Тропикариум-океанариум',                                     en: 'Tropicarium-Oceanarium' },
    { domain: 'nyolcesfel.hu',                ru: 'Дом мастерских «Нёльцешфель»',                               en: 'Nyolcésfél creative house' },
    { domain: 'makovecz.hu',                  ru: 'Фонд Имре Маковеца',                                         en: 'Imre Makovecz Foundation' },
    { domain: 'economx.hu',                   ru: 'Деловой новостной портал',                                   en: 'Business news portal' },
    { domain: 'budapestinfo.hu',              ru: 'Официальная туристическая информация Будапешта',             en: 'Official Budapest tourist information' },
    { domain: 'kavelabor.hu',                 ru: 'Блог о кофейной культуре',                                   en: 'Coffee culture blog' },
    { domain: 'juranyihaz.hu',                ru: 'Дом Юраньи, центр независимых искусств',                     en: 'Jurányi House, independent arts centre' },
    { domain: 'epa.oszk.hu',                  ru: 'Архив электронной периодики Национальной библиотеки Сечени', en: 'Electronic Periodicals Archive, National Széchényi Library' },
    { domain: 'whc.unesco.org',               ru: 'Центр всемирного наследия ЮНЕСКО',                           en: 'UNESCO World Heritage Centre' },
    { domain: 'muveszkavehaz.com',            ru: 'Кофейня «Мювес»',                                            en: 'Művész Coffee House' },
    { domain: 'ppke.hu',                      ru: 'Католический университет имени Петера Пазманя',              en: 'Pázmány Péter Catholic University' },
    { domain: 'hdke.hu',                      ru: 'Центр памяти Холокоста',                                     en: 'Holocaust Memorial Center' },
    { domain: 'auguszt1870.hu',               ru: 'Кондитерская «Аугуст»',                                      en: 'Auguszt confectionery' },
    { domain: 'zuglo.hu',                     ru: 'Официальный сайт XIV района (Зугло)',                        en: 'Official website of District XIV (Zugló)' },
    { domain: 'bunkerturak.hu',               ru: 'Экскурсии по бомбоубежищам',                                 en: 'Bunker tours' },
  ],
}
