import type { AboutData } from './types'

// Extracted from wiki_rural_travel/web/src/page-about.ts, preserving the display
// order of the rendered list. 66 sources.
export const ruralAbout: AboutData = {
  topics: {
    ru: 'природа, архитектура, история, транспорт, культура',
    en: 'nature, architecture, history, transport, culture',
  },
  sources: [
    { domain: 'ilovedunakanyar.hu',        ru: 'Путеводитель по достопримечательностям Излучины Дуная',           en: 'Travel guide to the Danube Bend' },
    { domain: 'visittata.com',             ru: 'Туристический портал Таты и района',                              en: 'Tourism portal for Tata and district' },
    { domain: 'visitesztergom.hu',         ru: 'Туристический портал Эстергома',                                  en: 'Tourism portal for Esztergom' },
    { domain: 'termeszetjaro.hu',          ru: 'Маршрутный туристический портал',                                 en: 'Hiking and route portal' },
    { domain: 'kirandulastippek.hu',       ru: 'Портал туристических советов',                                    en: 'Travel tips portal' },
    { domain: 'kirandulastervezo.hu',      ru: 'Планировщик туристических маршрутов',                             en: 'Route planner' },
    { domain: 'turisztikairegio.hu',       ru: 'Региональный туристический портал',                               en: 'Regional tourism portal' },
    { domain: 'programturizmus.hu',        ru: 'Туристические программы',                                         en: 'Tourism programmes' },
    { domain: 'trekhunt.com',              ru: 'Туристический гид',                                               en: 'Travel guide' },
    { domain: 'komoot.com',                ru: 'Туристическая платформа',                                         en: 'Tourism platform' },
    { domain: 'slovakia.travel',           ru: 'Официальный туристический портал Словакии',                       en: 'Official tourism portal of Slovakia' },
    { domain: 'travelguide.sk',            ru: 'Словацкий путеводитель по достопримечательностям',                en: 'Slovak travel guide' },
    { domain: 'zahorie.info',              ru: 'Туристическая ассоциация Загорья',                                en: 'Záhorie tourist association' },
    { domain: 'hiking.dennikn.sk',         ru: 'Туристические и путевые статьи (Denník N)',                       en: 'Hiking and travel articles (Denník N)' },
    { domain: 'naucnechodniky.eu',         ru: 'Портал познавательных троп Словакии',                             en: 'Educational trails portal (Slovakia)' },
    { domain: 'kamnavylet.sk',             ru: 'Портал однодневных вылазок (Словакия)',                           en: 'Day-trip portal (Slovakia)' },
    { domain: 'birdingplaces.eu',          ru: 'Портал мест для бёрдвотчинга',                                    en: 'Birdwatching sites portal' },
    { domain: 'medievalheritage.eu',       ru: 'Каталог средневекового наследия Словакии',                        en: 'Medieval heritage catalogue for Slovakia' },
    { domain: 'kozepkoritemplom.hu',       ru: 'Средневековые храмы Верхней Венгрии',                             en: 'Medieval churches of Upper Hungary' },
    { domain: 'funzine.hu',                ru: 'Журнал о местах и событиях',                                      en: 'Places and events magazine' },
    { domain: 'turistamagazin.hu',         ru: 'Туристический журнал',                                            en: 'Hiking magazine' },
    { domain: 'welovebudapest.com',        ru: 'Блог о Будапеште и окрестностях',                                 en: 'Blog about Budapest and surroundings' },
    { domain: 'femina.hu',                 ru: 'Венгерский туристический журнал',                                 en: 'Hungarian travel magazine' },
    { domain: 'hu.wikipedia.org',          ru: 'Венгерская Википедия',                                            en: 'Hungarian Wikipedia' },
    { domain: 'en.wikipedia.org',          ru: 'Английская Википедия',                                            en: 'English Wikipedia' },
    { domain: 'de.wikipedia.org',          ru: 'Немецкая Википедия',                                              en: 'German Wikipedia' },
    { domain: 'sk.wikipedia.org',          ru: 'Словацкая Википедия',                                             en: 'Slovak Wikipedia' },
    { domain: 'nagymaros.hu',              ru: 'Официальный сайт Надьмароша',                                     en: 'Official website of Nagymaros' },
    { domain: 'zsambek.hu',                ru: 'Официальный сайт Жамбека',                                        en: 'Official website of Zsámbék' },
    { domain: 'zsambekinfo.hu',            ru: 'Туристическая ассоциация Жамбекского котлована',                  en: 'Tourist association of the Zsámbék Basin' },
    { domain: 'nagymarosiplebania.hu',     ru: 'Сайт прихода Надьмароша',                                         en: 'Nagymaros parish website' },
    { domain: 'esztergom.hu',              ru: 'Официальный сайт Эстергома',                                      en: 'Official website of Esztergom' },
    { domain: 'oroszlany.hu',              ru: 'Официальный сайт Орослани',                                       en: 'Official website of Oroszlány' },
    { domain: 'bernolakovo.sk',            ru: 'Официальный сайт Бернолаково',                                    en: 'Official website of Bernolákovo' },
    { domain: 'ruszt.hu',                  ru: 'Официальный сайт Руста (Burgenland)',                             en: 'Official website of Rust (Burgenland)' },
    { domain: 'heviz.hu',                  ru: 'Официальный сайт Хевиза',                                         en: 'Official website of Hévíz' },
    { domain: 'senica.sk',                 ru: 'Официальный сайт Сеницы',                                         en: 'Official website of Senica' },
    { domain: 'roznava.sk',                ru: 'Официальный сайт Рожнявы',                                        en: 'Official website of Rožňava' },
    { domain: 'belapatfalva.hu',           ru: 'Официальный сайт Белапатфальвы',                                  en: 'Official website of Bélapátfalva' },
    { domain: 'diosgyorivar.hu',           ru: 'Замок Диошдьёр',                                                  en: 'Diósgyőr Castle' },
    { domain: 'barlangfurdo.hu',           ru: 'Пещерная купальня Мишкольцтапольцы',                              en: 'Miskolctapolca Cave Bath' },
    { domain: 'menesgazdasag.hu',          ru: 'Государственный конный завод Сильвашварад',                       en: 'Szilvásvárad State Stud Farm' },
    { domain: 'kekesteto.hu',              ru: 'Туристический сайт Кекештетё',                                    en: 'Kékestető tourist site' },
    { domain: 'visiteger.com',             ru: 'Туристический портал Эгера',                                      en: 'Eger tourism portal' },
    { domain: 'bazilikaeger.hu',           ru: 'Эгерская базилика',                                               en: 'Eger Basilica' },
    { domain: 'minareteger.hu',            ru: 'Эгерский минарет',                                                en: 'Eger Minaret' },
    { domain: 'egricsillagvizsgalo.hu',    ru: 'Обсерватория в Лицее, Эгер',                                      en: 'Lyceum Observatory, Eger' },
    { domain: 'szentbertalankincstar.hu',  ru: 'Сокровищница церкви Св. Варфоломея, Дьёндьёш',                    en: 'St Bartholomew\'s Church Treasury, Gyöngyös' },
    { domain: 'gyongyos.hu',               ru: 'Официальный сайт Дьёндьёша',                                      en: 'Official website of Gyöngyös' },
    { domain: 'szilvasvarad.hu',           ru: 'Официальный сайт Сильвашварада',                                  en: 'Official website of Szilvásvárad' },
    { domain: 'herend.com',                ru: 'Херендская фарфоровая мануфактура',                               en: 'Herend Porcelain Manufactory' },
    { domain: 'szantodpuszta.hu',          ru: 'Усадьба Сантодпуста',                                             en: 'Szántódpuszta Manor Farm' },
    { domain: 'nof.hu',                    ru: 'Национальная компания по развитию наследия (NÖF)',                en: 'National Heritage Development Nonprofit (NÖF)' },
    { domain: 'kalocsa.hu',                ru: 'Официальный сайт Калочи',                                         en: 'Official website of Kalocsa' },
    { domain: 'podolinec.eu',              ru: 'Официальный сайт Подолинца',                                      en: 'Official website of Podolínec' },
    { domain: 'balmazujvaros.hu',          ru: 'Официальный сайт Балмазуйвароша',                                 en: 'Official website of Balmazújváros' },
    { domain: 'semseykastely.hu',          ru: 'Усадьба Шемшеи и Музей Андора Шемшеи',                            en: 'Semsey Manor and Andor Semsey Museum' },
    { domain: 'feketekeramia.eu',          ru: 'Мастерская чёрной керамики Фазекаша',                             en: 'Fazekas black pottery workshop' },
    { domain: 'nadudvarifazekas.hu',       ru: 'Гончар Ференц Фазекаш, Надудвар',                                 en: 'Potter Ferenc Fazekas, Nádudvar' },
    { domain: 'parokia.hu',                ru: 'Сайты реформатских общин',                                        en: 'Reformed congregation websites' },
    { domain: 'zahorskaves.sk',            ru: 'Официальный сайт Загорской Веси',                                 en: 'Official website of Záhorská Ves' },
    { domain: 'turizmuskalocsa.hu',        ru: 'Туристический портал Калочи',                                     en: 'Kalocsa tourism portal' },
    { domain: 'kalocsaiertektar.hu',       ru: 'Реестр местных ценностей Калочи',                                 en: 'Kalocsa local heritage register' },
    { domain: 'astriceum.hu',              ru: 'Архиепископский музей Астрицеум',                                 en: 'Astriceum Archiepiscopal Museum' },
    { domain: 'asztrik.hu',                ru: 'Калочско-Кечкеметская архиепархия: архив и библиотека',           en: 'Archdiocese of Kalocsa-Kecskemét: archive and library' },
    { domain: 'lexikon.katolikus.hu',      ru: 'Венгерский католический лексикон',                                en: 'Hungarian Catholic Lexicon' },
    { domain: 'knp.hu',                    ru: 'Национальный парк Кишкуньшаг',                                    en: 'Kiskunság National Park' },
    { domain: 'bugacpuszta.hu',            ru: 'Бугацкая пуста: чарда Карикаш и табун',                           en: 'Bugac Puszta: Karikás Csárda and stud' },
    { domain: 'magyar-ertekmentes.hu',     ru: 'Фонд сохранения ценностей KÉRA',                                  en: 'KÉRA heritage foundation' },
    { domain: 'slovensky-kras.eu',         ru: 'Туристический портал Словацкого карста',                          en: 'Slovak Karst tourism portal' },
    { domain: 'bratislavaregion.travel',   ru: 'Туристический портал Братиславского края',                        en: 'Bratislava Region tourism portal' },
    { domain: 'ticsenica.sk',              ru: 'Туристический центр Сеницы',                                      en: 'Senica tourist information centre' },
    { domain: 'slovago.sk',                ru: 'Туристический портал slovago.sk',                                 en: 'slovago.sk tourism portal' },
    { domain: 'zgjm.sk',                   ru: 'Загорская галерея Яна Мудроха',                                   en: 'Ján Mudroch Záhorie Gallery' },
    { domain: 'zahorskemuzeum.sk',         ru: 'Загорский музей в Скалице',                                       en: 'Záhorie Museum, Skalica' },
    { domain: 'podolinec.redemptoristi.sk', ru: 'Монастырь редемптористов в Подолинце',                           en: 'Redemptorist monastery, Podolínec' },
    { domain: 'neusiedlamsee.at',          ru: 'Официальный туристический сайт Нойзидл-ам-Зее',                   en: 'Official tourism website of Neusiedl am See' },
    { domain: 'burgenland.info',           ru: 'Официальный туристический портал Бургенланда',                    en: 'Official tourism portal of Burgenland' },
    { domain: 'skhu.eu',                   ru: 'Программа приграничного сотрудничества Словакия–Венгрия (HUSK)',  en: 'Slovakia–Hungary cross-border cooperation (HUSK)' },
    { domain: 'iza.sk',                    ru: 'Официальный сайт Ижи',                                            en: 'Official website of Iža' },
    { domain: 'visegradmuzeum.hu',         ru: 'Музей Вишеграда',                                                 en: 'Visegrád Museum' },
    { domain: 'hajozasimuzeum.hu',         ru: 'Музей судоходства в Зебегене',                                    en: 'Nautical Museum, Zebegény' },
    { domain: 'danubiana.sk',              ru: 'Музей современного искусства Danubiana Meulensteen',              en: 'Danubiana Meulensteen Art Museum' },
    { domain: 'azaumtabor.hu',             ru: 'Римский лагерь Азаум (Алмашфюзитё)',                              en: 'Azaum Roman Camp, Almásfüzitő' },
    { domain: 'muzeum.sk',                 ru: 'Каталог музеев Словакии (muzeum.sk)',                             en: 'Slovak Museum catalogue (muzeum.sk)' },
    { domain: 'pestbuda.hu',               ru: 'Историко-архитектурный журнал о Будапеште и регионе',             en: 'Historical and architectural journal about Budapest and region' },
    { domain: 'mnl.gov.hu',                ru: 'Национальный архив Венгрии',                                      en: 'National Archives of Hungary' },
    { domain: 'varlexikon.hu',             ru: 'Энциклопедия замков и крепостей',                                 en: 'Castle and fortress encyclopaedia' },
    { domain: 'kastelyok.com',             ru: 'База данных замков и усадеб Венгрии',                             en: 'Database of Hungarian castles and manor houses' },
    { domain: 'mizsambekunk.hu',           ru: 'Культурный центр Жамбека',                                        en: 'Zsámbék Cultural Centre' },
    { domain: 'bacskainemetek.hu',         ru: 'Ресурс об этнических немцах Дунайского бассейна',                 en: 'Resource on ethnic Germans of the Danube Basin' },
    { domain: 'dunakanyarkult.blog.hu',    ru: 'Культурно-исторический блог Fábián Erika',                        en: 'Cultural history blog by Fábián Erika' },
    { domain: 'vizmerce.blog.hu',          ru: 'Исторический блог о судоходстве',                                 en: 'Historical blog on waterway transport' },
    { domain: 'ittjartam.hu',              ru: 'Путешественнический блог',                                        en: 'Travel blog' },
    { domain: 'elmenynektek.hu',           ru: 'Туристический блог о местах Венгрии и Австрии',                   en: 'Tourism blog about places in Hungary and Austria' },
    { domain: 'netkoffer.hu',              ru: 'Портал туристических советов и достопримечательностей',           en: 'Travel tips and sights portal' },
    { domain: 'welovebalaton.hu',          ru: 'Туристический портал региона Балатон',                            en: 'Balaton travel portal' },
    { domain: 'balatontipp.hu',            ru: 'Портал советов и смотровых точек Балатона',                       en: 'Balaton tips and viewpoints portal' },
    { domain: 'balcsi.net',                ru: 'Портал культурных объектов Балатона',                             en: 'Balaton cultural sites portal' },
    { domain: 'neusiedlersee.com',         ru: 'Туристический портал района Нойзидлерзее / Фертё',                en: 'Tourism portal for the Neusiedler See / Fertő region' },
    { domain: 'kalandzona.blog.hu',        ru: 'Блог о заброшенных местах',                                       en: 'Blog about abandoned places' },
    { domain: 'retropolisz.wordpress.com', ru: 'Блог о социалистической архитектуре',                             en: 'Blog on socialist architecture' },
    { domain: 'europepilgrime.eu',         ru: 'Портал паломнических маршрутов Европы',                           en: 'Pilgrimage destinations portal' },
    { domain: 'sovidom.sk',                ru: 'Культурно-исторический ресурс о Верхней Венгрии (на венгерском)', en: 'Cultural and historical resource on Upper Hungary (Hungarian)' },
    { domain: 'makovecz.hu',               ru: 'Фонд Маковеца — каталог построек органической архитектуры',       en: 'Makovecz Foundation — catalogue of organic architecture buildings' },
    { domain: 'yachter.sk',                ru: 'YACHTER CLUB Modrá Čajka — паром Чунново–Хамуляково',             en: 'YACHTER CLUB Modrá Čajka — Čunovo–Hamuliakovo ferry' },
    { domain: 'kompmenetrend.hu',          ru: 'Расписания дунайских паромов',                                    en: 'Danube ferry timetables' },
    { domain: 'kompok-revek.hu',           ru: 'Справочник паромов и переправ Венгрии',                           en: 'Directory of Hungarian ferries and crossings' },
    { domain: 'szentendrekomp.hu',         ru: 'Паром Сентендре–Сигетмоностор',                                   en: 'Szentendre–Szigetmonostor ferry' },
    { domain: 'bahart.hu',                 ru: 'Балатонское пароходство (BAHART)',                                en: 'Balaton Shipping Company (BAHART)' },
    { domain: 'kompazahorskaves.moderneobce.sk', ru: 'Паром Загорска Вес–Ангерн', en: 'Záhorská Ves–Angern ferry' },
    { domain: 'hungarianottomanwars.com',  ru: 'Замки и история венгерско-османских войн',                        en: 'Castles and history of the Hungarian–Ottoman wars' },
    { domain: 'oroksegnapok.gov.hu',       ru: 'Дни культурного наследия Венгрии',                                en: 'Hungarian Heritage Days' },
    { domain: 'mkik.hu',                   ru: 'Венгерская торгово-промышленная палата',                          en: 'Hungarian Chamber of Commerce and Industry' },
    { domain: 'bparchiv.hu',               ru: 'Будапештский городской архив',                                    en: 'Budapest City Archives' },
    { domain: 'dunaipoly.hu',              ru: 'Национальный парк Дунай-Ипой',                                    en: 'Danube–Ipoly National Park' },
    { domain: 'bnpi.hu',                   ru: 'Национальный парк Бюкк',                                          en: 'Bükk National Park' },
    { domain: 'ssj.sk',                    ru: 'Управление словацких пещер',                                      en: 'Slovak Caves Administration' },
    { domain: 'snm.sk',                    ru: 'Словацкий национальный музей',                                    en: 'Slovak National Museum' },
    { domain: 'banmuz.sk',                 ru: 'Горняцкий музей в Рожняве',                                       en: 'Mining Museum in Rožňava' },
    { domain: 'muzeumspisa.com',           ru: 'Музей Спиша',                                                     en: 'Spiš Museum' },
    { domain: 'nemzetijelkepek.hu',        ru: 'Гербы венгерских населённых пунктов',                             en: 'Coats of arms of Hungarian settlements' },
    { domain: 'eszakhirnok.com',           ru: 'Новостной портал Северной Венгрии',                               en: 'Northern Hungary news portal' },
    { domain: 'partlap.hu',                ru: 'Региональный новостной портал Partlap',                           en: 'Partlap regional news portal' },
    { domain: 'kalohirek.hu',              ru: 'Новостной портал Калочи',                                         en: 'Kalocsa news portal' },
    { domain: 'hiros.hu',                  ru: 'Новостной портал Кечкемета hiros.hu',                             en: 'hiros.hu news portal' },
    { domain: 'asb.sk',                    ru: 'Архитектурный журнал ASB',                                        en: 'ASB architecture magazine' },
    { domain: 'imbezirk.at',               ru: 'Региональный портал im-Bezirk.at',                                en: 'im-Bezirk.at regional portal' },
    { domain: 'dorfzeitung.com',           ru: 'Региональная газета Dorfzeitung',                                 en: 'Dorfzeitung regional paper' },
    { domain: 'mek.oszk.hu',               ru: 'Венгерская электронная библиотека',                               en: 'Hungarian Electronic Library' },
    { domain: 'skanzen.hu',                ru: 'Венгерский музей под открытым небом: управление домов-музеев',    en: 'Hungarian Open Air Museum: heritage houses' },
    { domain: 'kozterkep.hu',              ru: 'Каталог общественной скульптуры Венгрии',                         en: 'Hungarian public art catalogue' },
    { domain: 'egertermal.hu',             ru: 'Купальни Эгера',                                                  en: 'Eger baths' },
    { domain: 'gyongyos.ofm.hu',           ru: 'Францисканский монастырь Дьёндьёша',                              en: 'Franciscan friary of Gyöngyös' },
    { domain: 'gyfk.hu',                   ru: 'Францисканская библиотека Дьёндьёша',                             en: 'Franciscan Library of Gyöngyös' },
    { domain: 'nhmus.hu',                  ru: 'Венгерский музей естествознания и Музей Матры',                   en: 'Hungarian Natural History Museum and Mátra Museum' },
    { domain: 'likebalaton.hu',            ru: 'Портал о Балатоне LikeBalaton',                                   en: 'LikeBalaton portal' },
    { domain: 'csodalatosbalaton.hu',      ru: 'Портал о Балатоне CsodalatosBalaton',                             en: 'CsodalatosBalaton portal' },
    { domain: 'guideathand.com',           ru: 'Путеводитель Guide@Hand',                                         en: 'Guide@Hand travel guide' },
    { domain: 'szantodpuszta.click.hu',    ru: 'Сайт о Сантодпусте',                                              en: 'Szántódpuszta fan site' },
    { domain: 'telekialapitvany.hu',       ru: 'Фонд Телеки Ласло',                                               en: 'Teleki László Foundation' },
    { domain: 'vamosplebania.hu',          ru: 'Приход Немешвамош',                                               en: 'Nemesvámos parish' },
    { domain: 'miserend.hu',               ru: 'Каталог храмов Венгрии Miserend',                                 en: 'Miserend church directory' },
    { domain: 'muemlekem.hu',              ru: 'Портал памятников Műemlékem',                                     en: 'Műemlékem heritage portal' },
    { domain: 'vefleveltar.hu',            ru: 'Архив Веспремской архиепархии',                                   en: 'Archives of the Archdiocese of Veszprém' },
    { domain: 'beautifulslovakia.sk',      ru: 'Туристический портал Beautiful Slovakia',                         en: 'Beautiful Slovakia travel portal' },
    { domain: 'gotickacesta.sk',           ru: 'Готический путь: готические памятники Словакии',                  en: 'Gothic Route: Gothic monuments of Slovakia' },
    { domain: 'virtualne.sk',              ru: 'Туристический портал Virtualne.sk',                               en: 'Virtualne.sk travel portal' },
    { domain: 'stvr.sk',                   ru: 'Словацкое телевидение и радио (STVR)',                            en: 'Slovak Television and Radio (STVR)' },
    { domain: 'aranymonostor.hu',          ru: 'Визит-центр «Золотой монастырь», Бугац',                          en: 'Aranymonostor Visitor Centre, Bugac' },
    { domain: 'schoffergyujtemeny.hu',     ru: 'Собрание Николя Шёффера, Калоча',                                 en: 'Nicolas Schöffer Collection, Kalocsa' },
    { domain: 'museum-digital.org',        ru: 'Цифровые коллекции музеев (museum-digital)',                      en: 'Museum digital collections (museum-digital)' },
    { domain: 'hellohungary.hu',           ru: 'Туристический портал Hello Hungary',                              en: 'Hello Hungary tourism portal' },
    { domain: 'mult-kor.hu',               ru: 'Исторический журнал Múlt-kor',                                    en: 'Múlt-kor history magazine' },
    { domain: 'zoldhang.hu',               ru: 'Экологический портал Zöld Hang',                                  en: 'Zöld Hang environmental portal' },
    { domain: 'magyarnemzet.hu',           ru: 'Газета Magyar Nemzet',                                            en: 'Magyar Nemzet newspaper' },
    { domain: 'index.hu',                  ru: 'Новостной портал Index',                                          en: 'Index news portal' },
    { domain: 'baon.hu',                   ru: 'Новостной портал медье Бач-Кишкун',                               en: 'Bács-Kiskun county news portal' },
    { domain: 'kalocsatv.hu',              ru: 'Телевидение Калочи',                                              en: 'Kalocsa local television' },
    { domain: 'zemplenkalandpark.hu',      ru: 'Парк активного отдыха «Земплен», Шаторальяуйхей',                 en: 'Zemplén Adventure Park, Sátoraljaújhely' },
    { domain: 'fuzervara.hu',              ru: 'Замок Фюзер',                                                     en: 'Füzér Castle' },
    { domain: 'boldogkovara.hu',           ru: 'Замок Болдогкё',                                                  en: 'Boldogkő Castle' },
    { domain: 'dornyaymuzeum.hu',          ru: 'Музей Белы Дорняи, Шалготарьян',                                  en: 'Dornyay Béla Museum, Salgótarján' },
    { domain: 'erdeikirandulasok.hu',      ru: 'Портал лесных экскурсий Ipolyerdő',                               en: 'Ipolyerdő forest excursions portal' },
    { domain: 'tokaj.hu',                  ru: 'Официальный сайт Токая',                                          en: 'Official website of Tokaj' },
    { domain: 'tokaj-turizmus.hu',         ru: 'Туристический портал Токая',                                      en: 'Tokaj tourism portal' },
    { domain: 'tokajimuzeum.hu',           ru: 'Токайский музей',                                                 en: 'Tokaj Museum' },
    { domain: 'sarospatak.hu',             ru: 'Туристический сайт Шарошпатака',                                  en: 'Sárospatak tourism site' },
    { domain: 'rakoczimuzeum.hu',          ru: 'Музей Ракоци, Шарошпатак',                                        en: 'Rákóczi Museum, Sárospatak' },
    { domain: 'patakcollege.hu',           ru: 'Научные собрания Шарошпатакской реформатской коллегии',           en: 'Scholarly Collections of the Sárospatak Reformed College' },
    { domain: 'srkmuzeum.hu',              ru: 'Музей Реформатской коллегии, Шарошпатак',                         en: 'Reformed College Museum, Sárospatak' },
    { domain: 'anp.hu',                    ru: 'Национальный парк Аггтелек',                                      en: 'Aggtelek National Park' },
    { domain: 'edeleny-kastely.hu',        ru: 'Дворец в Эделене',                                                en: 'Edelény Palace' },
    { domain: 'bathorimuzeum.hu',          ru: 'Музей Батори Иштвана, Ньирбатор',                                 en: 'Báthori István Museum, Nyírbátor' },
    { domain: 'fogadalmitemplom.hu',       ru: 'Обетный храм, Сегед',                                             en: 'Votive Church, Szeged' },
    { domain: 'domlatogatokozpont.hu',     ru: 'Визит-центр Сегедского собора',                                   en: 'Szeged Cathedral Visitor Centre' },
    { domain: 'tornyaimuzeum.hu',          ru: 'Музей Торняи Яноша, Ходмезёвашархей',                             en: 'Tornyai János Museum, Hódmezővásárhely' },
    { domain: 'visitgyula.com',            ru: 'Туристический портал Дюлы',                                       en: 'Gyula tourism portal' },
    { domain: 'gyulavara.hu',              ru: 'Крепость Дюла',                                                   en: 'Gyula Castle' },
    { domain: 'pepikert.hu',               ru: 'Сарвашский арборетум',                                            en: 'Szarvas Arboretum' },
    { domain: 'opusztaszer.hu',            ru: 'Мемориальный парк Опустасер',                                     en: 'Ópusztaszer Heritage Park' },
    { domain: 'csongrad.hu',               ru: 'Официальный сайт Чонграда',                                       en: 'Official website of Csongrád' },
    { domain: 'csongradfurdo.hu',          ru: 'Купальня Чонграда',                                               en: 'Csongrád bath' },
    { domain: 'abaligetibarlang.hu',       ru: 'Абалигетская пещера',                                             en: 'Abaliget Cave' },
    { domain: 'pecsvaradivar.hu',          ru: 'Печварадский замок',                                              en: 'Pécsvárad Castle' },
    { domain: 'siklosivar.hu',             ru: 'Шиклошский замок',                                                en: 'Siklós Castle' },
    { domain: 'harkanyfurdo.hu',           ru: 'Харканьская лечебная купальня',                                   en: 'Harkány Medicinal Spa' },
    { domain: 'villanyiborvidek.hu',       ru: 'Туристический портал Виланьского винодельческого района',         en: 'Villány wine region tourism portal' },
    { domain: 'vilagoroksegpecs.hu',       ru: 'Объекты Всемирного наследия Печа',                                en: 'Pécs World Heritage sites' },
    { domain: 'pecsipuspokseg.hu',         ru: 'Туристический сайт Печского епископства',                         en: 'Pécs Diocese tourism site' },
    { domain: 'pecsiegyhazmegye.hu',       ru: 'Печская епархия',                                                 en: 'Diocese of Pécs' },
    { domain: 'zsolnaynegyed.hu',          ru: 'Культурный квартал Жолнаи',                                       en: 'Zsolnay Cultural Quarter' },
    { domain: 'smmi.hu',                   ru: 'Музей Риппль-Ронаи медье Шомодь',                                 en: 'Rippl-Rónai Museum of Somogy County' },
    { domain: 'varszigetvar.hu',           ru: 'Сигетварская крепость',                                           en: 'Szigetvár Castle' },
    { domain: 'zselicicsillagpark.hu',     ru: 'Звёздный парк Желич',                                             en: 'Zselic Starry Sky Park' },
    { domain: 'szigetvar.hu',              ru: 'Официальный сайт Сигетвара',                                      en: 'Official website of Szigetvár' },
    { domain: 'eo.wikipedia.org',          ru: 'Википедия на эсперанто',                                          en: 'Esperanto Wikipedia' },
    { domain: 'ddnp.hu',                   ru: 'Национальный парк Дунай — Драва',                                 en: 'Danube–Drava National Park' },
    { domain: 'mohacsibusojaras.hu',       ru: 'Мохачский Бушояраш — официальный сайт',                           en: 'Mohács Busójárás official site' },
    { domain: 'kanizsaidorottyamuzeum.hu', ru: 'Музей Канижаи Доротьи, Мохач',                                    en: 'Kanizsai Dorottya Museum, Mohács' },
    { domain: 'jpm.hu',                    ru: 'Музей Януса Паннония, Печ',                                       en: 'Janus Pannonius Museum, Pécs' },
    { domain: 'jakovalihaszandzsami.org',  ru: 'Мечеть Яковали Хасана',                                           en: 'Mosque of Yakovalı Hasan' },
    { domain: 'tvtoronypecs.hu',           ru: 'Печская телебашня',                                               en: 'Pécs TV Tower' },
    { domain: 'sellye.hu',                 ru: 'Официальный сайт Шейе',                                           en: 'Official website of Sellye' },
    { domain: 'furdoszovetseg.hu',         ru: 'Венгерская ассоциация купален',                                   en: 'Hungarian Baths Association' },
    { domain: 'en.wikivoyage.org',         ru: 'Wikivoyage, свободный путеводитель',                              en: 'Wikivoyage, the free travel guide' },
    { domain: 'hetedhetorszag.hu',         ru: 'Венгерский путеводитель',                                         en: 'Hungarian travel guide' },
    { domain: 'funiq.hu',                  ru: 'Венгерский портал о путешествиях и досуге',                       en: 'Hungarian travel and leisure portal' },
    { domain: 'termalfurdo.hu',            ru: 'Портал термальных купален Венгрии',                               en: 'Hungarian thermal bath portal' },
    { domain: 'bacskiskun.hu',             ru: 'Туристический портал медье Бач-Кишкун',                           en: 'Bács-Kiskun County tourism portal' },
    { domain: 'gyongyos-matra.hu',         ru: 'Туристическое объединение Дьёндьёш-Матра',                        en: 'Gyöngyös-Mátra tourist association' },
    { domain: 'matrahegy.hu',              ru: 'Туристический портал Матры',                                      en: 'Mátra tourist portal' },
    { domain: 'museum.hu',                 ru: 'Венгерский портал музеев',                                        en: 'Hungarian museum portal' },
    { domain: 'belapatfalvaturizmus.hu',   ru: 'Туристический портал Белапатфальвы',                              en: 'Bélapátfalva tourism portal' },
    { domain: 'podlesok.com',              ru: 'Туристический центр Подлесок (Словацкий рай)',                    en: 'Podlesok tourist centre (Slovak Paradise)' },
    { domain: 'orszagjaro.net',            ru: 'Трэвел-блог «Орсагъяро»',                                         en: 'Országjáró travel blog' },
    { domain: 'traveladdict.hu',           ru: 'Венгерский трэвел-блог',                                          en: 'Hungarian travel blog' },
    { domain: 'utazom.com',                ru: 'Венгерский портал о путешествиях',                                en: 'Hungarian travel portal' },
    { domain: 'aktivkalandor.hu',          ru: 'Портал походных и активных маршрутов',                            en: 'Hiking and outdoor routes portal' },
    { domain: 'i-dest.com',                ru: 'Путеводитель по направлениям',                                    en: 'Destination guide' },
    { domain: 'kornyeke.hu',               ru: 'Местные путеводители по городам вокруг Будапешта',                en: 'Local guides to towns around Budapest' },
    { domain: 'amultemlekei.hu',           ru: 'Блог о памятниках старины Венгрии',                               en: 'Blog on Hungarian historic monuments' },
    { domain: 'osmaradvanyok.hu',          ru: 'Каталог венгерских замков и руин',                                en: 'Catalogue of Hungarian castles and ruins' },
    { domain: 'symposion.hu',              ru: 'Международный художественный симпозиум на Веленцейском озере',    en: 'Velence Lake international artists\' symposium' },
    { domain: 'visithortobagy.com',        ru: 'Туристический портал Хортобади',                                  en: 'Hortobágy tourism portal' },
    { domain: 'info.szolnok.hu',           ru: 'Туристический портал Солнока',                                    en: 'Szolnok tourism portal' },
    { domain: 'iranycegled.hu',            ru: 'Туристический портал Цегледа',                                    en: 'Cegléd tourism portal' },
    { domain: 'iranykomarom.hu',           ru: 'Туристический портал Комарома',                                   en: 'Komárom tourism portal' },
    { domain: 'tourinformrackeve.hu',      ru: 'Туристическое бюро Рацкеве',                                      en: 'Tourinform Ráckeve' },
    { domain: 'kecskemet.hu',              ru: 'Официальный сайт Кечкемета',                                      en: 'Official website of Kecskemét' },
    { domain: 'martonvasar.hu',            ru: 'Официальный сайт Мартонвашара',                                   en: 'Official website of Martonvásár' },
    { domain: 'biatorbagy.hu',             ru: 'Официальный сайт Биаторбадя',                                     en: 'Official website of Biatorbágy' },
    { domain: 'herceghalom.hu',            ru: 'Официальный сайт Херцегхалома',                                   en: 'Official website of Herceghalom' },
    { domain: 'ocsa.hu',                   ru: 'Официальный сайт Очи',                                            en: 'Official website of Ócsa' },
    { domain: 'ullo.hu',                   ru: 'Официальный сайт Юллё',                                           en: 'Official website of Üllő' },
    { domain: 'szigetszentmiklos.hu',      ru: 'Официальный сайт Сигетсентмиклоша',                               en: 'Official website of Szigetszentmiklós' },
    { domain: 'medgyesegyhaza.hu',         ru: 'Официальный сайт Медьешедьхазы',                                  en: 'Official website of Medgyesegyháza' },
    { domain: 'nogradkozseg.hu',           ru: 'Официальный сайт села Ноград',                                    en: 'Official website of Nógrád village' },
    { domain: 'webetyek.hu',               ru: 'Местный портал Этека',                                            en: 'Etyek local portal' },
    { domain: 'alcsuti-arboretum.hu',      ru: 'Арборетум в Алчуте',                                              en: 'Alcsút Arboretum' },
    { domain: 'botanikuskert.hu',          ru: 'Национальный ботанический сад (Вацратот)',                        en: 'National Botanic Garden, Vácrátót' },
    { domain: 'sostoszekesfehervar.hu',    ru: 'Заповедник Шошто (Секешфехервар)',                                en: 'Sóstó nature reserve, Székesfehérvár' },
    { domain: 'automotormuzeum.hu',        ru: 'Музей автомобилей и мотоциклов Каали',                            en: 'Kaáli Car and Motorcycle Museum' },
    { domain: '1000evestemplom.hu',        ru: 'Руины Дёмёшского пропства',                                       en: 'Dömös provostry ruins' },
    { domain: 'hollokoivar.hu',            ru: 'Замок Холлокё',                                                   en: 'Hollókő Castle' },
    { domain: 'kisnanaivar.hu',            ru: 'Замок Кишнана',                                                   en: 'Kisnána Castle' },
    { domain: 'sumegvar.hu',               ru: 'Замок Шюмег',                                                     en: 'Sümeg Castle' },
    { domain: 'palotapince.hu',            ru: 'Палота-пинце (Шюмег)',                                            en: 'Palota Pince, Sümeg' },
    { domain: 'bratislavskykraj.sk',       ru: 'Братиславский самоуправляемый край',                              en: 'Bratislava Self-Governing Region' },
    { domain: 'kulturnecesty.sk',          ru: 'Культурные маршруты Словакии',                                    en: 'Cultural routes of Slovakia' },
    { domain: 'hradiskovaly.sk',           ru: 'Городище Валы и музей Великой Моравии (Бойна)',                   en: 'Valy hillfort and Great Moravia Museum, Bojná' },
    { domain: 'kamnavylety.sk',            ru: 'Портал идей для поездок по Словакии',                             en: 'Slovak trip ideas portal' },
    { domain: 'vypadni.sk',                ru: 'Словацкий портал советов для путешественников',                   en: 'Slovak travel tips portal' },
    { domain: 'danubeislands.sk',          ru: 'Портал о дунайских островах (Житный остров)',                     en: 'Danube islands portal (Žitný ostrov)' },
  ],
}
