import type { AboutData } from './types'

// Extracted from wiki_rural_travel/web/src/page-about.ts, preserving the display
// order of the rendered list. 66 sources.
export const ruralAbout: AboutData = {
  topics: {
    ru: 'природа, архитектура, история, транспорт, культура',
    en: 'nature, architecture, history, transport, culture',
  },
  sources: [
    { domain: 'ilovedunakanyar.hu',        ru: 'Путеводитель по достопримечательностям Излучины Дуная',           en: 'Travel guide to the Danube Bend' },
    { domain: 'visittata.com',             ru: 'Туристический портал Таты и района',                              en: 'Tourism portal for Tata and district' },
    { domain: 'visitesztergom.hu',         ru: 'Туристический портал Эстергома',                                  en: 'Tourism portal for Esztergom' },
    { domain: 'termeszetjaro.hu',          ru: 'Маршрутный туристический портал',                                 en: 'Hiking and route portal' },
    { domain: 'kirandulastippek.hu',       ru: 'Портал туристических советов',                                    en: 'Travel tips portal' },
    { domain: 'kirandulastervezo.hu',      ru: 'Планировщик туристических маршрутов',                             en: 'Route planner' },
    { domain: 'turisztikairegio.hu',       ru: 'Региональный туристический портал',                               en: 'Regional tourism portal' },
    { domain: 'programturizmus.hu',        ru: 'Туристические программы',                                         en: 'Tourism programmes' },
    { domain: 'trekhunt.com',              ru: 'Туристический гид',                                               en: 'Travel guide' },
    { domain: 'komoot.com',                ru: 'Туристическая платформа',                                         en: 'Tourism platform' },
    { domain: 'slovakia.travel',           ru: 'Официальный туристический портал Словакии',                       en: 'Official tourism portal of Slovakia' },
    { domain: 'travelguide.sk',            ru: 'Словацкий путеводитель по достопримечательностям',                en: 'Slovak travel guide' },
    { domain: 'zahorie.info',              ru: 'Туристическая ассоциация Загорья',                                en: 'Záhorie tourist association' },
    { domain: 'hiking.dennikn.sk',         ru: 'Туристические и путевые статьи (Denník N)',                       en: 'Hiking and travel articles (Denník N)' },
    { domain: 'naucnechodniky.eu',         ru: 'Портал познавательных троп Словакии',                             en: 'Educational trails portal (Slovakia)' },
    { domain: 'kamnavylet.sk',             ru: 'Портал однодневных вылазок (Словакия)',                           en: 'Day-trip portal (Slovakia)' },
    { domain: 'birdingplaces.eu',          ru: 'Портал мест для бёрдвотчинга',                                    en: 'Birdwatching sites portal' },
    { domain: 'medievalheritage.eu',       ru: 'Каталог средневекового наследия Словакии',                        en: 'Medieval heritage catalogue for Slovakia' },
    { domain: 'kozepkoritemplom.hu',       ru: 'Средневековые храмы Верхней Венгрии',                             en: 'Medieval churches of Upper Hungary' },
    { domain: 'funzine.hu',                ru: 'Журнал о местах и событиях',                                      en: 'Places and events magazine' },
    { domain: 'turistamagazin.hu',         ru: 'Туристический журнал',                                            en: 'Hiking magazine' },
    { domain: 'welovebudapest.com',        ru: 'Блог о Будапеште и окрестностях',                                 en: 'Blog about Budapest and surroundings' },
    { domain: 'femina.hu',                 ru: 'Венгерский туристический журнал',                                 en: 'Hungarian travel magazine' },
    { domain: 'hu.wikipedia.org',          ru: 'Венгерская Википедия',                                            en: 'Hungarian Wikipedia' },
    { domain: 'en.wikipedia.org',          ru: 'Английская Википедия',                                            en: 'English Wikipedia' },
    { domain: 'de.wikipedia.org',          ru: 'Немецкая Википедия',                                              en: 'German Wikipedia' },
    { domain: 'sk.wikipedia.org',          ru: 'Словацкая Википедия',                                             en: 'Slovak Wikipedia' },
    { domain: 'nagymaros.hu',              ru: 'Официальный сайт Надьмароша',                                     en: 'Official website of Nagymaros' },
    { domain: 'zsambek.hu',                ru: 'Официальный сайт Жамбека',                                        en: 'Official website of Zsámbék' },
    { domain: 'zsambekinfo.hu',            ru: 'Туристическая ассоциация Жамбекского котлована',                  en: 'Tourist association of the Zsámbék Basin' },
    { domain: 'nagymarosiplebania.hu',     ru: 'Сайт прихода Надьмароша',                                         en: 'Nagymaros parish website' },
    { domain: 'esztergom.hu',              ru: 'Официальный сайт Эстергома',                                      en: 'Official website of Esztergom' },
    { domain: 'oroszlany.hu',              ru: 'Официальный сайт Орослани',                                       en: 'Official website of Oroszlány' },
    { domain: 'bernolakovo.sk',            ru: 'Официальный сайт Бернолаково',                                    en: 'Official website of Bernolákovo' },
    { domain: 'ruszt.hu',                  ru: 'Официальный сайт Руста (Burgenland)',                             en: 'Official website of Rust (Burgenland)' },
    { domain: 'neusiedlamsee.at',          ru: 'Официальный туристический сайт Нойзидл-ам-Зее',                   en: 'Official tourism website of Neusiedl am See' },
    { domain: 'burgenland.info',           ru: 'Официальный туристический портал Бургенланда',                    en: 'Official tourism portal of Burgenland' },
    { domain: 'skhu.eu',                   ru: 'Программа приграничного сотрудничества Словакия–Венгрия (HUSK)',  en: 'Slovakia–Hungary cross-border cooperation (HUSK)' },
    { domain: 'iza.sk',                    ru: 'Официальный сайт Ижи',                                            en: 'Official website of Iža' },
    { domain: 'visegradmuzeum.hu',         ru: 'Музей Вишеграда',                                                 en: 'Visegrád Museum' },
    { domain: 'hajozasimuzeum.hu',         ru: 'Музей судоходства в Зебегене',                                    en: 'Nautical Museum, Zebegény' },
    { domain: 'danubiana.sk',              ru: 'Музей современного искусства Danubiana Meulensteen',              en: 'Danubiana Meulensteen Art Museum' },
    { domain: 'azaumtabor.hu',             ru: 'Римский лагерь Азаум (Алмашфюзитё)',                              en: 'Azaum Roman Camp, Almásfüzitő' },
    { domain: 'muzeum.sk',                 ru: 'Каталог музеев Словакии (muzeum.sk)',                             en: 'Slovak Museum catalogue (muzeum.sk)' },
    { domain: 'pestbuda.hu',               ru: 'Историко-архитектурный журнал о Будапеште и регионе',             en: 'Historical and architectural journal about Budapest and region' },
    { domain: 'mnl.gov.hu',                ru: 'Национальный архив Венгрии',                                      en: 'National Archives of Hungary' },
    { domain: 'varlexikon.hu',             ru: 'Энциклопедия замков и крепостей',                                 en: 'Castle and fortress encyclopaedia' },
    { domain: 'kastelyok.com',             ru: 'База данных замков и усадеб Венгрии',                             en: 'Database of Hungarian castles and manor houses' },
    { domain: 'mizsambekunk.hu',           ru: 'Культурный центр Жамбека',                                        en: 'Zsámbék Cultural Centre' },
    { domain: 'bacskainemetek.hu',         ru: 'Ресурс об этнических немцах Дунайского бассейна',                 en: 'Resource on ethnic Germans of the Danube Basin' },
    { domain: 'dunakanyarkult.blog.hu',    ru: 'Культурно-исторический блог Fábián Erika',                        en: 'Cultural history blog by Fábián Erika' },
    { domain: 'vizmerce.blog.hu',          ru: 'Исторический блог о судоходстве',                                 en: 'Historical blog on waterway transport' },
    { domain: 'ittjartam.hu',              ru: 'Путешественнический блог',                                        en: 'Travel blog' },
    { domain: 'elmenynektek.hu',           ru: 'Туристический блог о местах Венгрии и Австрии',                   en: 'Tourism blog about places in Hungary and Austria' },
    { domain: 'netkoffer.hu',              ru: 'Портал туристических советов и достопримечательностей',           en: 'Travel tips and sights portal' },
    { domain: 'welovebalaton.hu',          ru: 'Туристический портал региона Балатон',                            en: 'Balaton travel portal' },
    { domain: 'balatontipp.hu',            ru: 'Портал советов и смотровых точек Балатона',                       en: 'Balaton tips and viewpoints portal' },
    { domain: 'balcsi.net',                ru: 'Портал культурных объектов Балатона',                             en: 'Balaton cultural sites portal' },
    { domain: 'neusiedlersee.com',         ru: 'Туристический портал района Нойзидлерзее / Фертё',                en: 'Tourism portal for the Neusiedler See / Fertő region' },
    { domain: 'kalandzona.blog.hu',        ru: 'Блог о заброшенных местах',                                       en: 'Blog about abandoned places' },
    { domain: 'retropolisz.wordpress.com', ru: 'Блог о социалистической архитектуре',                             en: 'Blog on socialist architecture' },
    { domain: 'europepilgrime.eu',         ru: 'Портал паломнических маршрутов Европы',                           en: 'Pilgrimage destinations portal' },
    { domain: 'sovidom.sk',                ru: 'Культурно-исторический ресурс о Верхней Венгрии (на венгерском)', en: 'Cultural and historical resource on Upper Hungary (Hungarian)' },
    { domain: 'makovecz.hu',               ru: 'Фонд Маковеца — каталог построек органической архитектуры',       en: 'Makovecz Foundation — catalogue of organic architecture buildings' },
    { domain: 'yachter.sk',                ru: 'YACHTER CLUB Modrá Čajka — паром Чунново–Хамуляково',             en: 'YACHTER CLUB Modrá Čajka — Čunovo–Hamuliakovo ferry' },
    { domain: 'kompmenetrend.hu',          ru: 'Расписания дунайских паромов',                                    en: 'Danube ferry timetables' },
    { domain: 'kompok-revek.hu',           ru: 'Справочник паромов и переправ Венгрии',                           en: 'Directory of Hungarian ferries and crossings' },
    { domain: 'szentendrekomp.hu',         ru: 'Паром Сентендре–Сигетмоностор',                                   en: 'Szentendre–Szigetmonostor ferry' },
    { domain: 'bahart.hu',                 ru: 'Балатонское пароходство (BAHART)',                                en: 'Balaton Shipping Company (BAHART)' },
    { domain: 'hungarianottomanwars.com',  ru: 'Замки и история венгерско-османских войн',                        en: 'Castles and history of the Hungarian–Ottoman wars' },
    { domain: 'oroksegnapok.gov.hu',       ru: 'Дни культурного наследия Венгрии',                                en: 'Hungarian Heritage Days' },
    { domain: 'mkik.hu',                   ru: 'Венгерская торгово-промышленная палата',                          en: 'Hungarian Chamber of Commerce and Industry' },
    { domain: 'bparchiv.hu',               ru: 'Будапештский городской архив',                                    en: 'Budapest City Archives' },
    { domain: 'dunaipoly.hu',              ru: 'Национальный парк Дунай-Ипой',                                    en: 'Danube–Ipoly National Park' },
    { domain: 'furdoszovetseg.hu',         ru: 'Венгерская ассоциация купален',                                   en: 'Hungarian Baths Association' },
    { domain: 'en.wikivoyage.org',         ru: 'Wikivoyage, свободный путеводитель',                              en: 'Wikivoyage, the free travel guide' },
    { domain: 'hetedhetorszag.hu',         ru: 'Венгерский путеводитель',                                         en: 'Hungarian travel guide' },
    { domain: 'funiq.hu',                  ru: 'Венгерский портал о путешествиях и досуге',                       en: 'Hungarian travel and leisure portal' },
    { domain: 'orszagjaro.net',            ru: 'Трэвел-блог «Орсагъяро»',                                         en: 'Országjáró travel blog' },
    { domain: 'traveladdict.hu',           ru: 'Венгерский трэвел-блог',                                          en: 'Hungarian travel blog' },
    { domain: 'utazom.com',                ru: 'Венгерский портал о путешествиях',                                en: 'Hungarian travel portal' },
    { domain: 'aktivkalandor.hu',          ru: 'Портал походных и активных маршрутов',                            en: 'Hiking and outdoor routes portal' },
    { domain: 'i-dest.com',                ru: 'Путеводитель по направлениям',                                    en: 'Destination guide' },
    { domain: 'kornyeke.hu',               ru: 'Местные путеводители по городам вокруг Будапешта',                en: 'Local guides to towns around Budapest' },
    { domain: 'amultemlekei.hu',           ru: 'Блог о памятниках старины Венгрии',                               en: 'Blog on Hungarian historic monuments' },
    { domain: 'osmaradvanyok.hu',          ru: 'Каталог венгерских замков и руин',                                en: 'Catalogue of Hungarian castles and ruins' },
    { domain: 'symposion.hu',              ru: 'Международный художественный симпозиум на Веленцейском озере',    en: 'Velence Lake international artists\' symposium' },
    { domain: 'visithortobagy.com',        ru: 'Туристический портал Хортобади',                                  en: 'Hortobágy tourism portal' },
    { domain: 'info.szolnok.hu',           ru: 'Туристический портал Солнока',                                    en: 'Szolnok tourism portal' },
    { domain: 'iranycegled.hu',            ru: 'Туристический портал Цегледа',                                    en: 'Cegléd tourism portal' },
    { domain: 'iranykomarom.hu',           ru: 'Туристический портал Комарома',                                   en: 'Komárom tourism portal' },
    { domain: 'tourinformrackeve.hu',      ru: 'Туристическое бюро Рацкеве',                                      en: 'Tourinform Ráckeve' },
    { domain: 'kecskemet.hu',              ru: 'Официальный сайт Кечкемета',                                      en: 'Official website of Kecskemét' },
    { domain: 'martonvasar.hu',            ru: 'Официальный сайт Мартонвашара',                                   en: 'Official website of Martonvásár' },
    { domain: 'biatorbagy.hu',             ru: 'Официальный сайт Биаторбадя',                                     en: 'Official website of Biatorbágy' },
    { domain: 'herceghalom.hu',            ru: 'Официальный сайт Херцегхалома',                                   en: 'Official website of Herceghalom' },
    { domain: 'ocsa.hu',                   ru: 'Официальный сайт Очи',                                            en: 'Official website of Ócsa' },
    { domain: 'ullo.hu',                   ru: 'Официальный сайт Юллё',                                           en: 'Official website of Üllő' },
    { domain: 'szigetszentmiklos.hu',      ru: 'Официальный сайт Сигетсентмиклоша',                               en: 'Official website of Szigetszentmiklós' },
    { domain: 'medgyesegyhaza.hu',         ru: 'Официальный сайт Медьешедьхазы',                                  en: 'Official website of Medgyesegyháza' },
    { domain: 'nogradkozseg.hu',           ru: 'Официальный сайт села Ноград',                                    en: 'Official website of Nógrád village' },
    { domain: 'webetyek.hu',               ru: 'Местный портал Этека',                                            en: 'Etyek local portal' },
    { domain: 'alcsuti-arboretum.hu',      ru: 'Арборетум в Алчуте',                                              en: 'Alcsút Arboretum' },
    { domain: 'botanikuskert.hu',          ru: 'Национальный ботанический сад (Вацратот)',                        en: 'National Botanic Garden, Vácrátót' },
    { domain: 'sostoszekesfehervar.hu',    ru: 'Заповедник Шошто (Секешфехервар)',                                en: 'Sóstó nature reserve, Székesfehérvár' },
    { domain: 'automotormuzeum.hu',        ru: 'Музей автомобилей и мотоциклов Каали',                            en: 'Kaáli Car and Motorcycle Museum' },
    { domain: '1000evestemplom.hu',        ru: 'Руины Дёмёшского пропства',                                       en: 'Dömös provostry ruins' },
    { domain: 'hollokoivar.hu',            ru: 'Замок Холлокё',                                                   en: 'Hollókő Castle' },
    { domain: 'kisnanaivar.hu',            ru: 'Замок Кишнана',                                                   en: 'Kisnána Castle' },
    { domain: 'sumegvar.hu',               ru: 'Замок Шюмег',                                                     en: 'Sümeg Castle' },
    { domain: 'palotapince.hu',            ru: 'Палота-пинце (Шюмег)',                                            en: 'Palota Pince, Sümeg' },
    { domain: 'bratislavskykraj.sk',       ru: 'Братиславский самоуправляемый край',                              en: 'Bratislava Self-Governing Region' },
    { domain: 'kulturnecesty.sk',          ru: 'Культурные маршруты Словакии',                                    en: 'Cultural routes of Slovakia' },
    { domain: 'hradiskovaly.sk',           ru: 'Городище Валы и музей Великой Моравии (Бойна)',                   en: 'Valy hillfort and Great Moravia Museum, Bojná' },
    { domain: 'kamnavylety.sk',            ru: 'Портал идей для поездок по Словакии',                             en: 'Slovak trip ideas portal' },
    { domain: 'vypadni.sk',                ru: 'Словацкий портал советов для путешественников',                   en: 'Slovak travel tips portal' },
    { domain: 'danubeislands.sk',          ru: 'Портал о дунайских островах (Житный остров)',                     en: 'Danube islands portal (Žitný ostrov)' },
  ],
}
